import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, writeFile, readFile, readdir, rm, access } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { scanWindows, runExportProcess } from "../dist/windows-scan.js";
import { parseCsvStream } from "../dist/index.js";
import { saveSnapshotBytes, validateSnapshotDestination } from "../dist/snapshots.js";

const csv = 'Generated by WizTree\nFile Name,Size,Allocated,Modified,Attributes,Files,Folders\n"C:\\Data\\",3,4096,2000/01/01,D,1,0\n"C:\\Data\\x.txt",3,4096,2000/01/01,,,\n';
const input = { targetPath: "C:\\Data", includeFiles: true, includeFolders: true, admin: false,
  treemap: false, timeoutSeconds: 5, maxEntries: 100, saveSnapshot: false };
async function setup(t) {
  const base = await mkdtemp(join(tmpdir(), "wiztree-lifecycle-fixture-"));
  t.after(() => rm(base, { recursive: true, force: true }));
  const sentinel = join(base, "existing-user.csv"); await writeFile(sentinel, "user CSV stays");
  return base;
}
const exportedPath = args => args.find(arg => arg.startsWith("/export=")).slice("/export=".length);

test("Windows successful exporter preserves options and deletes only its temporary CSV/PNG", async t => {
  const base = await setup(t); let temporary;
  const result = await scanWindows("mock-wiztree.exe", { ...input, treemap: true, filter: "*.txt", filterExclude: "cache", sortBy: "size" }, {
    temporaryParent: base, parseCsv: parseCsvStream,
    run: async args => {
      const path = exportedPath(args); temporary = dirname(path);
      assert.ok(args.includes("/exportfiles=1")); assert.ok(args.includes("/exportfolders=1"));
      assert.ok(args.includes("/filter=*.txt")); assert.ok(args.includes("/filterexclude=cache"));
      assert.ok(args.includes("/sortby=size")); assert.ok(args.includes("/admin=0"));
      await writeFile(path, csv);
      await writeFile(args.find(a => a.startsWith("/treemapimagefile=")).slice("/treemapimagefile=".length), Buffer.from([137,80,78,71]));
      return { stdout: "ok", stderr: "" };
    },
  });
  assert.equal(result.entries.length, 2); assert.equal(result.saved, undefined);
  assert.equal(result.image.data, Buffer.from([137,80,78,71]).toString("base64"));
  await assert.rejects(access(temporary));
  assert.deepEqual(await readdir(base), ["existing-user.csv"]);
  assert.equal(await readFile(join(base, "existing-user.csv"), "utf8"), "user CSV stays");
});

for (const failure of ["exporter", "parser"]) {
  test(`Windows ${failure} failure cleans owned temporary files and leaves existing CSV intact`, async t => {
    const base = await setup(t);
    await assert.rejects(scanWindows("mock", input, {
      temporaryParent: base,
      parseCsv: failure === "parser" ? async () => { throw new Error("parser failed"); } : parseCsvStream,
      run: async args => { await writeFile(exportedPath(args), csv);
        if (failure === "exporter") throw new Error("exporter failed");
        return { stdout: "", stderr: "" }; },
    }), /failed/);
    assert.deepEqual(await readdir(base), ["existing-user.csv"]);
  });
}

for (const kind of ["success", "failure", "cancel", "timeout"]) {
  test(`Windows lifecycle with actual Node fixture subprocess: ${kind}`, async t => {
    const base = await setup(t);
    const controller = new AbortController(); t.after(() => controller.abort());
    let temporary;
    const result = scanWindows("mock", { ...input, timeoutSeconds: kind === "timeout" ? 0.15 : 5 }, {
      temporaryParent: base, parseCsv: parseCsvStream,
      run: async (args, timeout, signal) => {
        const path = exportedPath(args); temporary = dirname(path);
        const script = `require("node:fs").writeFileSync(process.argv[1], ${JSON.stringify(csv)});` +
          (kind === "success" ? "" : kind === "failure" ? "process.exit(7);" : "setInterval(() => {}, 1000);");
        const running = runExportProcess([process.execPath, "-e", script, path], timeout, signal);
        // Attach rejection promptly while waiting for the fixture to create its CSV.
        running.catch(() => {});
        if (kind === "cancel") {
          const deadline = Date.now() + 2000;
          while (Date.now() < deadline) {
            try { await access(path); break; } catch { await new Promise(done => setTimeout(done, 5)); }
          }
          await access(path); controller.abort();
        }
        return running;
      },
    }, controller.signal);
    if (kind === "success") assert.equal((await result).entries.length, 2);
    else await assert.rejects(result, kind === "failure" ? /code 7/ : kind === "cancel" ? /cancelled/ : /timed out/);
    await assert.rejects(access(temporary));
    assert.deepEqual(await readdir(base), ["existing-user.csv"]);
  });
}

test("intentional Windows save preserves original CSV at exact requested name; duplicate never overwrites", async t => {
  const base = await setup(t); const directory = join(base, "intentional");
  const options = { ...input, saveSnapshot: true, snapshotDirectory: directory, snapshotName: "baseline.csv" };
  const deps = { temporaryParent: base, parseCsv: parseCsvStream,
    run: async args => { await writeFile(exportedPath(args), csv); return { stdout: "", stderr: "" }; } };
  const result = await scanWindows("mock", options, deps);
  assert.equal(result.saved.csvPath, join(directory, "baseline.csv"));
  assert.equal(await readFile(result.saved.csvPath, "utf8"), csv);
  await assert.rejects(scanWindows("mock", options, deps), /EEXIST/);
  assert.equal(await readFile(result.saved.csvPath, "utf8"), csv);
  assert.deepEqual((await readdir(base)).sort(), ["existing-user.csv", "intentional"]);
});

test("save requires explicit directory/name; no implicit timestamps or path traversal; single-file cap", async t => {
  const base = await setup(t);
  for (const [directory, name] of [[undefined, undefined], [base, undefined], ["relative", "x.csv"], [base, "../x.csv"], [base, "CON.csv"]]) {
    assert.throws(() => validateSnapshotDestination(directory, name));
  }
  await assert.rejects(scanWindows("mock", { ...input, saveSnapshot: true }, { temporaryParent: base, parseCsv: parseCsvStream }), /explicit/);
  await assert.rejects(saveSnapshotBytes(Buffer.alloc(32 * 1024 * 1024 + 1), join(base, "oversize"), "baseline.csv"), /32 MiB/);
  const aborted = new AbortController(); aborted.abort();
  await assert.rejects(saveSnapshotBytes("tiny", join(base, "cancelled"), "baseline.csv", aborted.signal), /abort/i);
  assert.deepEqual(await readdir(base), ["existing-user.csv"]);
});
