#!/usr/bin/env node
import { spawn } from "node:child_process";
import { createReadStream, existsSync } from "node:fs";
import { mkdir, readFile, readdir, stat, unlink } from "node:fs/promises";
import { basename, dirname, extname, join, resolve } from "node:path";
import { StringDecoder } from "node:string_decoder";
import { Transform } from "node:stream";
import { fileURLToPath, pathToFileURL } from "node:url";
import { parse } from "csv-parse";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

type WizTreeEntry = {
  path: string;
  size: number;
  allocated: number;
  modified?: string;
  attributes?: string;
  files?: number;
  folders?: number;
  isFolder: boolean;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = resolve(__dirname, "..");
const exportDir = process.env.WIZTREE_MCP_EXPORT_DIR
  ? resolve(process.env.WIZTREE_MCP_EXPORT_DIR)
  : join(projectRoot, "exports");
const isWindows = process.platform === "win32";

const server = new McpServer({
  name: "wiztree-mcp",
  version: "0.1.0",
});

function textResult(text: string) {
  return { content: [{ type: "text" as const, text }] };
}

function jsonResult(value: unknown) {
  return textResult(JSON.stringify(value));
}

function parseBytes(value: unknown): number {
  if (typeof value === "number") return value;
  const cleaned = String(value ?? "").replace(/[^\d.-]/g, "");
  const parsed = Number(cleaned);
  return Number.isFinite(parsed) ? parsed : 0;
}

function parseCount(value: unknown): number | undefined {
  if (value === undefined || value === null || value === "") return undefined;
  const parsed = Number(String(value).replace(/[^\d.-]/g, ""));
  return Number.isFinite(parsed) ? parsed : undefined;
}

function formatBytes(bytes: number): string {
  const units = ["B", "KB", "MB", "GB", "TB", "PB"];
  let value = Math.abs(bytes);
  let unit = 0;
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024;
    unit += 1;
  }
  const signed = bytes < 0 ? "-" : "";
  const decimals = unit === 0 ? 0 : value >= 100 ? 1 : 2;
  return `${signed}${value.toFixed(decimals)} ${units[unit]}`;
}

// --- CSV parsing (streaming + cache) ---------------------------------------

type ColumnMap = {
  path: number;
  size: number;
  allocated: number;
  modified: number;
  attributes: number;
  files: number;
  folders: number;
};

function resolveColumns(header: string[]): ColumnMap {
  const idx = (...names: string[]) =>
    header.findIndex((cell) => names.includes(cell.replace(/^\uFEFF/, "").trim()));
  return {
    path: idx("File Name", "ファイル名"),
    size: idx("Size", "サイズ"),
    allocated: idx("Allocated", "割り当て"),
    modified: idx("Modified", "更新日時"),
    attributes: idx("Attributes", "属性"),
    files: idx("Files", "ファイル数"),
    folders: idx("Folders", "フォルダー"),
  };
}

function findHeaderOffset(text: string): number {
  // Header may be quoted ("File Name",...) or bare (File Name,...), English or Japanese.
  const match = /(?:^|\n)"?(?:file name|ファイル名)"?\s*,/i.exec(text);
  if (!match) return -1;
  return match.index === 0 ? 0 : match.index + 1;
}

// Skips the WizTree preamble ("Generated by WizTree ...") before the header row.
function makePreambleSkipper(): Transform {
  const decoder = new StringDecoder("utf8");
  let buffer = "";
  let done = false;
  return new Transform({
    transform(chunk, _enc, cb) {
      if (done) {
        this.push(chunk);
        return cb();
      }
      buffer += decoder.write(chunk as Buffer);
      const stripped = buffer.replace(/^\uFEFF/, "");
      const offset = findHeaderOffset(stripped);
      if (offset >= 0) {
        done = true;
        this.push(Buffer.from(stripped.slice(offset), "utf8"));
        buffer = "";
      } else if (buffer.length > 2_000_000) {
        done = true;
        this.push(Buffer.from(stripped, "utf8"));
        buffer = "";
      }
      cb();
    },
    flush(cb) {
      if (!done) {
        buffer += decoder.end();
        const stripped = buffer.replace(/^\uFEFF/, "");
        const offset = findHeaderOffset(stripped);
        this.push(Buffer.from(offset >= 0 ? stripped.slice(offset) : stripped, "utf8"));
      }
      cb();
    },
  });
}

async function parseCsvStream(resolvedPath: string): Promise<WizTreeEntry[]> {
  const parser = parse({ relax_column_count: true, skip_empty_lines: true });
  const stream = createReadStream(resolvedPath);
  const skipper = makePreambleSkipper();
  stream.on("error", (error) => parser.destroy(error));
  skipper.on("error", (error) => parser.destroy(error));
  stream.pipe(skipper).pipe(parser);

  const entries: WizTreeEntry[] = [];
  let cols: ColumnMap | undefined;
  for await (const record of parser as AsyncIterable<string[]>) {
    if (!cols) {
      cols = resolveColumns(record);
      continue;
    }
    const path = (cols.path >= 0 ? String(record[cols.path] ?? "") : "").trim();
    if (!path) continue;

    const entry: WizTreeEntry = {
      path,
      size: parseBytes(cols.size >= 0 ? record[cols.size] : 0),
      allocated: parseBytes(cols.allocated >= 0 ? record[cols.allocated] : 0),
      isFolder: path.endsWith("\\") || path.endsWith("/"),
    };
    const modified = cols.modified >= 0 ? String(record[cols.modified] ?? "") : "";
    const attributes = cols.attributes >= 0 ? String(record[cols.attributes] ?? "") : "";
    const files = parseCount(cols.files >= 0 ? record[cols.files] : undefined);
    const folders = parseCount(cols.folders >= 0 ? record[cols.folders] : undefined);
    if (modified) entry.modified = modified;
    if (attributes) entry.attributes = attributes;
    if (files !== undefined) entry.files = files;
    if (folders !== undefined) entry.folders = folders;
    entries.push(entry);
  }
  return entries;
}

type CacheEntry = { key: string; mtimeMs: number; size: number; entries: WizTreeEntry[] };
const CACHE_LIMIT = 3;
const csvCache: CacheEntry[] = [];

async function readCsv(csvPath: string): Promise<WizTreeEntry[]> {
  const resolved = resolve(csvPath);
  if (!existsSync(resolved)) {
    throw new Error(
      `CSV not found: ${resolved}. Run scan_path first, or use list_snapshots to see available snapshots in ${exportDir}.`,
    );
  }
  const stats = await stat(resolved);
  const hitIndex = csvCache.findIndex(
    (entry) => entry.key === resolved && entry.mtimeMs === stats.mtimeMs && entry.size === stats.size,
  );
  if (hitIndex >= 0) {
    const [hit] = csvCache.splice(hitIndex, 1);
    csvCache.unshift(hit);
    return hit.entries;
  }
  const entries = await parseCsvStream(resolved);
  csvCache.unshift({ key: resolved, mtimeMs: stats.mtimeMs, size: stats.size, entries });
  while (csvCache.length > CACHE_LIMIT) csvCache.pop();
  return entries;
}

// --- Analysis helpers ------------------------------------------------------

function summarizeEntries(entries: WizTreeEntry[]) {
  const files = entries.filter((entry) => !entry.isFolder);
  const folders = entries.filter((entry) => entry.isFolder);
  const totalFileSize = files.reduce((sum, entry) => sum + entry.size, 0);
  const totalAllocated = files.reduce((sum, entry) => sum + entry.allocated, 0);
  const largestRoot = folders.reduce<WizTreeEntry | undefined>(
    (largest, entry) => (!largest || entry.size > largest.size ? entry : largest),
    undefined,
  );

  return {
    entries: entries.length,
    fileEntries: files.length,
    folderEntries: folders.length,
    totalFileSize,
    totalFileSizeHuman: formatBytes(totalFileSize),
    totalAllocated,
    totalAllocatedHuman: formatBytes(totalAllocated),
    largestFolder: largestRoot
      ? {
          path: largestRoot.path,
          size: largestRoot.size,
          sizeHuman: formatBytes(largestRoot.size),
          files: largestRoot.files,
          folders: largestRoot.folders,
        }
      : undefined,
  };
}

function selectTop(
  entries: WizTreeEntry[],
  kind: "files" | "folders" | "all",
  limit: number,
  by: "size" | "allocated",
): WizTreeEntry[] {
  return entries
    .filter((entry) => kind === "all" || (kind === "files" ? !entry.isFolder : entry.isFolder))
    .sort((a, b) => b[by] - a[by])
    .slice(0, limit);
}

function entryObject(entry: WizTreeEntry) {
  return {
    path: entry.path,
    kind: entry.isFolder ? "folder" : "file",
    size: entry.size,
    sizeHuman: formatBytes(entry.size),
    allocated: entry.allocated,
    allocatedHuman: formatBytes(entry.allocated),
    modified: entry.modified,
    files: entry.files,
    folders: entry.folders,
  };
}

// Compact tab-separated table to keep token counts low for list outputs.
function tableResult(header: string[], rows: string[][], preamble?: string) {
  const lines = [header.join("\t"), ...rows.map((row) => row.join("\t"))];
  const text = (preamble ? `${preamble}\n` : "") + lines.join("\n");
  return textResult(text);
}

function entriesTable(entries: WizTreeEntry[], preamble?: string) {
  return tableResult(
    ["sizeHuman", "kind", "path"],
    entries.map((entry) => [formatBytes(entry.size), entry.isFolder ? "folder" : "file", entry.path]),
    preamble,
  );
}

function extensionOf(entry: WizTreeEntry): string {
  const extension = extname(entry.path).toLowerCase();
  return extension || "[no extension]";
}

function normalizePath(path: string): string {
  return path.replace(/\//g, "\\").toLowerCase();
}

function commonPrefixLength(a: string, b: string): number {
  const max = Math.min(a.length, b.length);
  let i = 0;
  while (i < max && a[i] === b[i]) i += 1;
  return i;
}

// Direct children of folderPath, sorted by size descending.
function drillDown(entries: WizTreeEntry[], folderPath: string, limit: number) {
  let folderNorm = normalizePath(folderPath);
  if (!folderNorm.endsWith("\\")) folderNorm += "\\";

  const children: WizTreeEntry[] = [];
  let folderExists = false;
  for (const entry of entries) {
    const entryNorm = normalizePath(entry.path);
    if (entryNorm === folderNorm) {
      folderExists = true;
      continue;
    }
    if (!entryNorm.startsWith(folderNorm)) continue;
    folderExists = true;
    const remainder = entryNorm.slice(folderNorm.length).replace(/\\$/, "");
    if (remainder && !remainder.includes("\\")) children.push(entry);
  }

  if (!folderExists) {
    const suggestions = entries
      .filter((entry) => entry.isFolder)
      .map((entry) => ({ path: entry.path, score: commonPrefixLength(normalizePath(entry.path), folderNorm) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, 5)
      .filter((candidate) => candidate.score > 0)
      .map((candidate) => candidate.path);
    return { found: false as const, suggestions };
  }

  const sorted = children.sort((a, b) => b.size - a.size).slice(0, limit);
  return { found: true as const, children: sorted };
}

function globToRegExp(query: string): RegExp {
  const escaped = query.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*").replace(/\?/g, ".");
  return new RegExp(escaped, "i");
}

function searchEntries(
  entries: WizTreeEntry[],
  query: string,
  kind: "files" | "folders" | "all",
  limit: number,
) {
  const useGlob = query.includes("*") || query.includes("?");
  const regex = useGlob ? globToRegExp(query) : undefined;
  const needle = query.toLowerCase();
  const matcher = (path: string) => (regex ? regex.test(path) : path.toLowerCase().includes(needle));

  let totalSize = 0;
  let totalCount = 0;
  const matches: WizTreeEntry[] = [];
  for (const entry of entries) {
    if (kind !== "all" && (kind === "files" ? entry.isFolder : !entry.isFolder)) continue;
    if (!matcher(entry.path)) continue;
    totalSize += entry.size;
    totalCount += 1;
    matches.push(entry);
  }
  matches.sort((a, b) => b.size - a.size);
  return { rows: matches.slice(0, limit), totalSize, totalCount };
}

function parseModified(value: string): number | undefined {
  const parsed = Date.parse(value);
  if (!Number.isNaN(parsed)) return parsed;
  const match = value.match(/(\d{4})\/(\d{1,2})\/(\d{1,2})(?:[ T](\d{1,2}):(\d{2})(?::(\d{2}))?)?/);
  if (match) {
    const date = new Date(
      Number(match[1]),
      Number(match[2]) - 1,
      Number(match[3]),
      Number(match[4] ?? 0),
      Number(match[5] ?? 0),
      Number(match[6] ?? 0),
    );
    const time = date.getTime();
    return Number.isNaN(time) ? undefined : time;
  }
  return undefined;
}

function oldLargeFiles(
  entries: WizTreeEntry[],
  olderThanDays: number,
  minSizeBytes: number,
  limit: number,
  now: number = Date.now(),
) {
  const cutoff = now - olderThanDays * 24 * 60 * 60 * 1000;
  const matches: { entry: WizTreeEntry; modifiedMs: number }[] = [];
  for (const entry of entries) {
    if (entry.isFolder || entry.size < minSizeBytes || !entry.modified) continue;
    const modifiedMs = parseModified(entry.modified);
    if (modifiedMs === undefined || modifiedMs > cutoff) continue;
    matches.push({ entry, modifiedMs });
  }
  matches.sort((a, b) => b.entry.size - a.entry.size);
  return matches.slice(0, limit);
}

// --- WizTree executable ----------------------------------------------------

function findWizTreeCandidates(): string[] {
  const candidates = new Set<string>();
  const envPath = process.env.WIZTREE_PATH;
  if (envPath) candidates.add(envPath);

  const pathDirs = (process.env.PATH ?? "").split(";").filter(Boolean);
  for (const dir of pathDirs) {
    candidates.add(join(dir, "WizTree64.exe"));
    candidates.add(join(dir, "WizTree.exe"));
  }

  for (const root of [process.env.ProgramFiles, process.env["ProgramFiles(x86)"]].filter(Boolean) as string[]) {
    candidates.add(join(root, "WizTree", "WizTree64.exe"));
    candidates.add(join(root, "WizTree", "WizTree.exe"));
    candidates.add(join(root, "Antibody Software", "WizTree", "WizTree64.exe"));
    candidates.add(join(root, "Antibody Software", "WizTree", "WizTree.exe"));
  }

  candidates.add(join(projectRoot, "WizTree64.exe"));
  candidates.add(join(projectRoot, "WizTree.exe"));
  candidates.add(join(dirname(projectRoot), "WizTree", "WizTree64.exe"));
  candidates.add(join(dirname(projectRoot), "WizTree", "WizTree.exe"));

  return [...candidates];
}

function locateWizTree(explicitPath?: string): string | undefined {
  if (explicitPath && existsSync(explicitPath)) return explicitPath;
  return findWizTreeCandidates().find((candidate) => existsSync(candidate));
}

function safeName(input: string): string {
  return input.replace(/^[A-Za-z]:/, (drive) => drive.replace(":", "")).replace(/[\\/:*?"<>|\s]+/g, "_").replace(/^_+|_+$/g, "") || "scan";
}

async function runWizTree(args: string[], timeoutSeconds: number): Promise<{ stdout: string; stderr: string }> {
  return await new Promise((resolvePromise, reject) => {
    const child = spawn(args[0], args.slice(1), {
      windowsHide: true,
      stdio: ["ignore", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    const timeout = setTimeout(() => {
      // On Windows, kill the whole process tree; a plain kill can leave WizTree running.
      if (isWindows && child.pid) {
        try {
          spawn("taskkill", ["/pid", String(child.pid), "/t", "/f"], { windowsHide: true });
        } catch {
          child.kill();
        }
      } else {
        child.kill();
      }
      reject(new Error(`WizTree timed out after ${timeoutSeconds} seconds.`));
    }, timeoutSeconds * 1000);

    child.stdout?.on("data", (chunk) => {
      stdout += chunk.toString();
    });
    child.stderr?.on("data", (chunk) => {
      stderr += chunk.toString();
    });
    child.on("error", (error) => {
      clearTimeout(timeout);
      reject(error);
    });
    child.on("close", (code) => {
      clearTimeout(timeout);
      if (code === 0) {
        resolvePromise({ stdout, stderr });
      } else {
        reject(new Error(`WizTree exited with code ${code}.${stderr ? ` stderr: ${stderr}` : ""}`));
      }
    });
  });
}

async function imageContent(pngPath: string) {
  const data = await readFile(pngPath);
  return { type: "image" as const, data: data.toString("base64"), mimeType: "image/png" };
}

// --- Tools -----------------------------------------------------------------

server.registerTool(
  "locate_wiztree",
  {
    title: "Locate WizTree",
    description: "Find a WizTree executable using WIZTREE_PATH, PATH, and common install folders.",
    inputSchema: {},
  },
  async () => {
    const candidates = findWizTreeCandidates().map((candidate) => ({
      path: candidate,
      exists: existsSync(candidate),
    }));
    return jsonResult({
      found: candidates.find((candidate) => candidate.exists)?.path,
      candidates,
    });
  },
);

server.registerTool(
  "scan_path",
  {
    title: "Scan Path",
    description: "Run WizTree CSV export for a drive or folder. This is read-only and writes a CSV snapshot. Windows-only.",
    inputSchema: {
      targetPath: z.string().describe('Drive or folder to scan, such as "C:" or "D:\\Data".'),
      wiztreePath: z.string().optional().describe("Optional explicit path to WizTree64.exe or WizTree.exe."),
      includeFiles: z.boolean().default(true).describe("Include file rows in the export."),
      includeFolders: z.boolean().default(true).describe("Include folder rows in the export."),
      admin: z
        .boolean()
        .default(false)
        .describe(
          "Pass /admin=1 to WizTree for a faster low-level MFT scan. This triggers a Windows UAC elevation dialog; in an unattended environment the process will hang until the configured timeout.",
        ),
      filter: z.string().optional().describe('Optional WizTree include filter, such as "*.mp4".'),
      filterExclude: z.string().optional().describe('Optional WizTree exclude filter, such as "node_modules".'),
      sortBy: z.string().optional().describe('Optional WizTree sort option, such as "size".'),
      treemap: z.boolean().default(false).describe("Also export a 1024x768 treemap PNG beside the CSV."),
      timeoutSeconds: z.number().int().positive().max(3600).default(300),
    },
  },
  async (input) => {
    if (!isWindows) {
      return textResult("scan_path requires WizTree, which is Windows-only. This host is not Windows. CSV analysis tools still work on any platform.");
    }
    const wiztree = locateWizTree(input.wiztreePath);
    if (!wiztree) {
      return textResult("WizTree executable was not found. Set WIZTREE_PATH or pass wiztreePath.");
    }

    await mkdir(exportDir, { recursive: true });
    const stamp = new Date().toISOString().replace(/[:.]/g, "-");
    const base = `${safeName(input.targetPath)}_${stamp}`;
    const csvPath = join(exportDir, `${base}.csv`);
    const pngPath = join(exportDir, `${base}.png`);
    const args = [
      wiztree,
      input.targetPath,
      `/export=${csvPath}`,
      `/admin=${input.admin ? 1 : 0}`,
      `/exportfiles=${input.includeFiles ? 1 : 0}`,
      `/exportfolders=${input.includeFolders ? 1 : 0}`,
    ];

    if (input.filter) args.push(`/filter=${input.filter}`);
    if (input.filterExclude) args.push(`/filterexclude=${input.filterExclude}`);
    if (input.sortBy) args.push(`/sortby=${input.sortBy}`);
    if (input.treemap) {
      args.push(`/treemapimagefile=${pngPath}`);
      args.push("/treemapimagewidth=1024");
      args.push("/treemapimageheight=768");
      args.push("/treemapimagefreespace=0");
      args.push("/treemapimageshowallocated=1");
    }

    const result = await runWizTree(args, input.timeoutSeconds);
    const entries = existsSync(csvPath) ? await readCsv(csvPath) : [];
    const hasTreemap = input.treemap && existsSync(pngPath);
    const content: (
      | { type: "text"; text: string }
      | { type: "image"; data: string; mimeType: string }
    )[] = [
      {
        type: "text",
        text: JSON.stringify({
          wiztree,
          targetPath: input.targetPath,
          csvPath,
          treemapPath: hasTreemap ? pngPath : undefined,
          summary: summarizeEntries(entries),
          stdout: result.stdout.trim() || undefined,
          stderr: result.stderr.trim() || undefined,
        }),
      },
    ];
    if (hasTreemap) content.push(await imageContent(pngPath));
    return { content };
  },
);

server.registerTool(
  "analyze_csv",
  {
    title: "Analyze CSV",
    description: "Summarize an existing WizTree CSV snapshot.",
    inputSchema: {
      csvPath: z.string().describe("Path to a WizTree CSV export."),
      topLimit: z.number().int().positive().max(100).default(20),
    },
  },
  async (input) => {
    const entries = await readCsv(input.csvPath);
    return jsonResult({
      csvPath: resolve(input.csvPath),
      summary: summarizeEntries(entries),
      largestFiles: selectTop(entries, "files", input.topLimit, "size").map(entryObject),
      largestFolders: selectTop(entries, "folders", input.topLimit, "size").map(entryObject),
    });
  },
);

server.registerTool(
  "top_entries",
  {
    title: "Top Entries",
    description: "List the largest files, folders, or all rows from a WizTree CSV snapshot.",
    inputSchema: {
      csvPath: z.string(),
      kind: z.enum(["files", "folders", "all"]).default("all"),
      by: z.enum(["size", "allocated"]).default("size"),
      limit: z.number().int().positive().max(500).default(50),
    },
  },
  async (input) => {
    const entries = await readCsv(input.csvPath);
    return entriesTable(selectTop(entries, input.kind, input.limit, input.by));
  },
);

server.registerTool(
  "list_snapshots",
  {
    title: "List Snapshots",
    description: "List WizTree CSV snapshots in the export directory, newest first.",
    inputSchema: {},
  },
  async () => {
    if (!existsSync(exportDir)) {
      return tableResult(["mtime", "sizeHuman", "path"], [], `No export directory yet: ${exportDir}`);
    }
    const names = await readdir(exportDir);
    const snapshots = [];
    for (const name of names) {
      if (!name.toLowerCase().endsWith(".csv")) continue;
      const full = join(exportDir, name);
      const stats = await stat(full);
      snapshots.push({ path: full, size: stats.size, mtimeMs: stats.mtimeMs });
    }
    snapshots.sort((a, b) => b.mtimeMs - a.mtimeMs);
    return tableResult(
      ["mtime", "sizeHuman", "path"],
      snapshots.map((snap) => [new Date(snap.mtimeMs).toISOString(), formatBytes(snap.size), snap.path]),
      `${snapshots.length} snapshot(s) in ${exportDir}`,
    );
  },
);

server.registerTool(
  "drill_down",
  {
    title: "Drill Down",
    description: "List the direct children (files and folders) of a folder within a WizTree snapshot, sorted by size.",
    inputSchema: {
      csvPath: z.string(),
      folderPath: z.string().describe('Folder path inside the snapshot, such as "C:\\Users\\me\\AppData".'),
      limit: z.number().int().positive().max(500).default(50),
    },
  },
  async (input) => {
    const entries = await readCsv(input.csvPath);
    const result = drillDown(entries, input.folderPath, input.limit);
    if (!result.found) {
      const hint = result.suggestions.length
        ? `\nClosest folders:\n${result.suggestions.join("\n")}`
        : "";
      return textResult(`Folder not found in snapshot: ${input.folderPath}${hint}`);
    }
    return entriesTable(result.children, `Direct children of ${input.folderPath} (${result.children.length} shown)`);
  },
);

server.registerTool(
  "search_entries",
  {
    title: "Search Entries",
    description: "Search a WizTree snapshot for paths matching a substring or glob (* and ?), sorted by size, with total matched size and count.",
    inputSchema: {
      csvPath: z.string(),
      query: z.string().describe('Substring or glob to match against paths, such as "node_modules" or "*.mp4".'),
      kind: z.enum(["files", "folders", "all"]).default("all"),
      limit: z.number().int().positive().max(500).default(50),
    },
  },
  async (input) => {
    const entries = await readCsv(input.csvPath);
    const { rows, totalSize, totalCount } = searchEntries(entries, input.query, input.kind, input.limit);
    const preamble = `Matches: ${totalCount}, total size: ${formatBytes(totalSize)} (${totalSize} bytes), showing top ${rows.length}`;
    return entriesTable(rows, preamble);
  },
);

server.registerTool(
  "old_large_files",
  {
    title: "Old Large Files",
    description: "Find large files not modified for a long time, sorted by size.",
    inputSchema: {
      csvPath: z.string(),
      olderThanDays: z.number().positive().default(365).describe("Only files older than this many days."),
      minSizeBytes: z.number().nonnegative().default(100 * 1024 * 1024).describe("Minimum file size in bytes (default 100 MB)."),
      limit: z.number().int().positive().max(500).default(50),
    },
  },
  async (input) => {
    const entries = await readCsv(input.csvPath);
    const matches = oldLargeFiles(entries, input.olderThanDays, input.minSizeBytes, input.limit);
    return tableResult(
      ["sizeHuman", "modified", "path"],
      matches.map(({ entry }) => [formatBytes(entry.size), entry.modified ?? "", entry.path]),
      `Files >= ${formatBytes(input.minSizeBytes)} not modified in ${input.olderThanDays} days (${matches.length} shown)`,
    );
  },
);

server.registerTool(
  "extension_summary",
  {
    title: "Extension Summary",
    description: "Aggregate file usage by extension from a WizTree CSV snapshot.",
    inputSchema: {
      csvPath: z.string(),
      limit: z.number().int().positive().max(500).default(100),
    },
  },
  async (input) => {
    const entries = (await readCsv(input.csvPath)).filter((entry) => !entry.isFolder);
    const byExtension = new Map<string, { extension: string; files: number; size: number; allocated: number }>();
    for (const entry of entries) {
      const extension = extensionOf(entry);
      const current = byExtension.get(extension) ?? { extension, files: 0, size: 0, allocated: 0 };
      current.files += 1;
      current.size += entry.size;
      current.allocated += entry.allocated;
      byExtension.set(extension, current);
    }

    const rows = [...byExtension.values()]
      .sort((a, b) => b.size - a.size)
      .slice(0, input.limit);
    return tableResult(
      ["sizeHuman", "files", "extension"],
      rows.map((row) => [formatBytes(row.size), String(row.files), row.extension]),
    );
  },
);

server.registerTool(
  "compare_csv",
  {
    title: "Compare CSV",
    description: "Compare two WizTree CSV snapshots by path and report the largest changes.",
    inputSchema: {
      beforeCsvPath: z.string(),
      afterCsvPath: z.string(),
      kind: z.enum(["files", "folders", "all"]).default("all"),
      limit: z.number().int().positive().max(500).default(50),
    },
  },
  async (input) => {
    const keep = (entry: WizTreeEntry) =>
      input.kind === "all" || (input.kind === "files" ? !entry.isFolder : entry.isFolder);
    const before = (await readCsv(input.beforeCsvPath)).filter(keep);
    const after = (await readCsv(input.afterCsvPath)).filter(keep);
    const beforeMap = new Map(before.map((entry) => [entry.path.toLowerCase(), entry]));
    const afterMap = new Map(after.map((entry) => [entry.path.toLowerCase(), entry]));
    const keys = new Set([...beforeMap.keys(), ...afterMap.keys()]);
    const changes = [...keys].map((key) => {
      const oldEntry = beforeMap.get(key);
      const newEntry = afterMap.get(key);
      const path = newEntry?.path ?? oldEntry?.path ?? key;
      const beforeSize = oldEntry?.size ?? 0;
      const afterSize = newEntry?.size ?? 0;
      const delta = afterSize - beforeSize;
      return {
        path,
        kind: (newEntry ?? oldEntry)?.isFolder ? "folder" : "file",
        delta,
        status: oldEntry && newEntry ? "changed" : oldEntry ? "removed" : "added",
      };
    });

    const growth = changes.filter((change) => change.delta > 0).sort((a, b) => b.delta - a.delta).slice(0, input.limit);
    const shrinkage = changes.filter((change) => change.delta < 0).sort((a, b) => a.delta - b.delta).slice(0, input.limit);
    const toRows = (list: typeof changes) => list.map((c) => [formatBytes(c.delta), c.status, c.kind, c.path]);
    const header = ["deltaHuman", "status", "kind", "path"];
    const growthText = ["# growth", header.join("\t"), ...toRows(growth).map((r) => r.join("\t"))].join("\n");
    const shrinkText = ["# shrinkage", header.join("\t"), ...toRows(shrinkage).map((r) => r.join("\t"))].join("\n");
    return textResult(`${growthText}\n\n${shrinkText}`);
  },
);

server.registerTool(
  "get_treemap",
  {
    title: "Get Treemap",
    description: "Return a previously generated treemap PNG as an image.",
    inputSchema: {
      pngPath: z.string().describe("Path to a treemap PNG generated by scan_path."),
    },
  },
  async (input) => {
    const resolved = resolve(input.pngPath);
    if (!existsSync(resolved)) {
      return textResult(`Treemap PNG not found: ${resolved}`);
    }
    return { content: [await imageContent(resolved)] };
  },
);

server.registerTool(
  "cleanup_snapshots",
  {
    title: "Cleanup Snapshots",
    description: "Delete older CSV/PNG exports from the export directory, keeping the most recent ones. Never touches files outside the export directory.",
    inputSchema: {
      keepLatest: z.number().int().nonnegative().max(1000).default(5).describe("Number of most recent snapshots (by base name) to keep."),
    },
  },
  async (input) => {
    if (!existsSync(exportDir)) {
      return jsonResult({ exportDir, deleted: [], kept: [], note: "Export directory does not exist yet." });
    }
    const names = await readdir(exportDir);
    // Group CSV/PNG by base name (a snapshot); track newest mtime per group.
    const groups = new Map<string, { files: string[]; mtimeMs: number }>();
    for (const name of names) {
      const lower = name.toLowerCase();
      if (!lower.endsWith(".csv") && !lower.endsWith(".png")) continue;
      const full = join(exportDir, name);
      const stats = await stat(full);
      const base = name.slice(0, name.length - extname(name).length);
      const group = groups.get(base) ?? { files: [], mtimeMs: 0 };
      group.files.push(full);
      group.mtimeMs = Math.max(group.mtimeMs, stats.mtimeMs);
      groups.set(base, group);
    }
    const ordered = [...groups.values()].sort((a, b) => b.mtimeMs - a.mtimeMs);
    const kept = ordered.slice(0, input.keepLatest);
    const toDelete = ordered.slice(input.keepLatest);

    const deleted: string[] = [];
    for (const group of toDelete) {
      for (const file of group.files) {
        const resolved = resolve(file);
        // Safety: only ever delete inside the export directory.
        if (resolved !== exportDir && !resolved.startsWith(exportDir + "\\") && !resolved.startsWith(exportDir + "/")) {
          continue;
        }
        await unlink(resolved);
        deleted.push(resolved);
      }
    }
    return jsonResult({
      exportDir,
      keptSnapshots: kept.length,
      deleted,
      keptFiles: kept.flatMap((group) => group.files.map((file) => basename(file))),
    });
  },
);

// --- Startup ---------------------------------------------------------------

async function startServer() {
  if (!isWindows) {
    process.stderr.write(
      "wiztree-mcp: WizTree is Windows-only. scan_path will not run on this host, but CSV analysis tools work anywhere.\n",
    );
  }
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

const isMain = Boolean(process.argv[1]) && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  await startServer();
}

export {
  readCsv,
  parseCsvStream,
  drillDown,
  searchEntries,
  oldLargeFiles,
  summarizeEntries,
  selectTop,
  parseModified,
  formatBytes,
};
export type { WizTreeEntry };
